name: Al3HG
version: '${version}'
main: al3ncar.al3hg.Al3HgPlugin
api-version: '1.21.11'
load: STARTUP
author: Dedectr
description: Hunger Games para Paper com AdvancedSlimePaper

permissions:
  hg.admin:
    description: Permissão para comandos do plugin

commands:
  hgc:
    description: Comando principal do al3HG (start, fs, stop, rest, reload, help)
    usage: /hgc <start|fs|stop|rest|reload|help>
    permission: hg.admin
